package org.tourgune.mdp.booking.utils;

public class Constants {

	/**
	 * VARIABLES
	 */
		// Tasks del script (deben coincidir con amazon_config.properties), variable "BS_TASK"
		public final static String BS_CONSTANT_TASK_PRICES_HDE				= "BS_CONSTANT_TASK_PRICES_HDE";
		public final static String BS_CONSTANT_TASK_PRICES					= "BS_CONSTANT_TASK_PRICES";
		public final static String BS_CONSTANT_TASK_RATINGS					= "BS_CONSTANT_TASK_RATINGS";
		public final static String BS_CONSTANT_TASK_REVIEWS					= "BS_CONSTANT_TASK_REVIEWS";
		public final static String BS_CONSTANT_TASK_SERVICES				= "BS_CONSTANT_TASK_SERVICES";
		
		
		// Constants
		public final static String BS_SEGMENT_TYPE						= "BS_SEGMENT_TYPE";
		
		public final static String BS_CONSTANT_TASK 					= "BS_CONSTANT_TASK";
		public final static String BS_CONSTANT_DATA 					= "BS_CONSTANT_DATA";
		public final static String BS_CONSTANT_REGIONID					= "BS_CONSTANT_REGIONID";
		public final static String BS_CONSTANT_ACCOMMODATIONID 					= "BS_CONSTANT_ACCOMMODATIONID";
		public final static String BS_CONSTANT_OFFERDATE 				= "BS_CONSTANT_OFFERDATE";
		public final static String BS_CONSTANT_INDATE 					= "BS_CONSTANT_INDATE";
		public final static String BS_CONSTANT_OUTDATE 					= "BS_CONSTANT_OUTDATE";
		public final static String BS_CONSTANT_COUNTRY					= "BS_CONSTANT_COUNTRY";
	
//		public final static String BS_CONSTANT_SEPARATOR_TEXT			= "BS_CONSTANT_SEPARATOR_TEXT";
//		public final static String BS_CONSTANT_SEPARATOR_CLASS			= "BS_CONSTANT_SEPARATOR_CLASS";
		
		public final static String BS_CONSTANT_DOUBLEROOM 				= "BS_CONSTANT_DOUBLEROOM";
		public final static String BS_CONSTANT_TWINROOM 				= "BS_CONSTANT_TWINROOM";
		public final static String BS_CONSTANT_MAX_PEOPLE_REGEX_JQ		= "BS_CONSTANT_MAX_PEOPLE_REGEX_1";
		public final static String BS_CONSTANT_MAX_PEOPLE_REGEX_JQ_2	= "BS_CONSTANT_MAX_PEOPLE_REGEX_2";
		public final static String BS_CONSTANT_MAX_PEOPLE_REGEX_I		= "BS_CONSTANT_MAX_PEOPLE_REGEX_3";

		// HDE PRICES
		public final static String BS_CONSTANT_HDEPRICE_ACCOMMODATIONIDCHANNEL	  	= "BS_CONSTANT_HDEPRICE_ACCOMMODATIONIDCHANNEL";
		public final static String BS_CONSTANT_HDEPRICE_ACCOMMODATIONNAME 		  	= "BS_CONSTANT_HDEPRICE_ACCOMMODATIONNAME";
		public final static String BS_CONSTANT_HDEPRICE_HDEPRICE 		  	= "BS_CONSTANT_HDEPRICE_HDEPRICE";
		public final static String BS_CONSTANT_HDEPRICE_ACCOMMODATION_COORDS_ATTR 	= "BS_CONSTANT_HDEPRICE_ACCOMMODATION_COORDS_ATTR";
		public final static String BS_CONSTANT_HDEPRICE_CATEGORY			= "BS_CONSTANT_HDEPRICE_CATEGORY";
		public final static String BS_CONSTANT_HDEPRICE_LATITUDE			= "BS_CONSTANT_HDEPRICE_LATITUDE";
		public final static String BS_CONSTANT_HDEPRICE_LONGITUDE			= "BS_CONSTANT_HDEPRICE_LONGITUDE";
		public final static String BS_CONSTANT_HDEPRICE_URL					= "BS_CONSTANT_HDEPRICE_URL";
		public final static String BS_CONSTANT_HDEPRICE_HREF				= "BS_CONSTANT_HDEPRICE_HREF";
		public final static String BS_CONSTANT_HDEPRICE_ID					= "BS_CONSTANT_HDEPRICE_ID";
		public final static String BS_CONSTANT_HDEPRICE_TITLE				= "BS_CONSTANT_HDEPRICE_TITLE";
		
		// PRODUCTS
		public final static String BS_CONSTANT_PRODUCT_NAME 			= "BS_CONSTANT_PRODUCT_NAME";
		public final static String BS_CONSTANT_PRODUCT_OCCUPANCY 		= "BS_CONSTANT_PRODUCT_OCCUPANCY";
		public final static String BS_CONSTANT_PRODUCT_CHILD 			= "BS_CONSTANT_PRODUCT_CHILD";
		public final static String BS_CONSTANT_PRODUCT_BREAKFASTPRICE 	= "BS_CONSTANT_PRODUCT_BREAKFASTPRICE";
		public final static String BS_CONSTANT_PRODUCT_BREAKFAST 		= "BS_CONSTANT_PRODUCT_BREAKFAST";
		public final static String BS_CONSTANT_PRODUCT_HALF 			= "BS_CONSTANT_PRODUCT_HALF";
		public final static String BS_CONSTANT_PRODUCT_FULL 			= "BS_CONSTANT_PRODUCT_FULL";
		public final static String BS_CONSTANT_PRODUCT_ALL 				= "BS_CONSTANT_PRODUCT_ALL";
		public final static String BS_CONSTANT_PRODUCT_CANCELLATION 	= "BS_CONSTANT_PRODUCT_CANCELLATION";
		public final static String BS_CONSTANT_PRODUCT_PAYSTAY 			= "BS_CONSTANT_PRODUCT_PAYSTAY";
		public final static String BS_CONSTANT_PRODUCT_PAYLATER 		= "BS_CONSTANT_PRODUCT_PAYLATER";
		public final static String BS_CONSTANT_PRODUCT_NONRFUNDABLE 	= "BS_CONSTANT_PRODUCT_NONRFUNDABLE";
		public final static String BS_CONSTANT_PRODUCT_PRICE		 	= "BS_CONSTANT_PRODUCT_PRICE";
		
		// RATINGS
		public final static String BS_CONSTANT_RATING_USERSEGMENT 		= "BS_CONSTANT_RATING_USERSEGMENT";
		public final static String BS_CONSTANT_RATING_DATA_ATTR 		= "BS_CONSTANT_RATING_DATA_ATTR";
		public final static String BS_CONSTANT_RATING_DATA_ATTR_TTL		= "BS_CONSTANT_RATING_DATA_ATTR_TTL";
		public final static String BS_CONSTANT_RATING_SERVICES 			= "BS_CONSTANT_RATING_SERVICES";
		public final static String BS_CONSTANT_RATING_STAFF				= "BS_CONSTANT_RATING_STAFF";
		public final static String BS_CONSTANT_RATING_CLEAN				= "BS_CONSTANT_RATING_CLEAN";
		public final static String BS_CONSTANT_RATING_LOCATION 			= "BS_CONSTANT_RATING_LOCATION";
		public final static String BS_CONSTANT_RATING_COMFORT 			= "BS_CONSTANT_RATING_COMFORT";
		public final static String BS_CONSTANT_RATING_VALUE 			= "BS_CONSTANT_RATING_VALUE";
		public final static String BS_CONSTANT_RATING_WIFI	 			= "BS_CONSTANT_RATING_WIFI";
		public final static String BS_CONSTANT_RATING_AVG				= "BS_CONSTANT_RATING_AVG";
		public final static String BS_CONSTANT_RATING_TTL_USERS			= "BS_CONSTANT_RATING_TTL_USERS";
		
		// REVIEWS
		public final static String BS_CONSTANT_REVIEW_DATE_FORMAT		= "BS_CONSTANT_REVIEW_DATE_FORMAT";
		public final static String BS_CONSTANT_REVIEW_TYPE_TRIP 		= "BS_CONSTANT_REVIEW_TYPE_TRIP";
		public final static String BS_CONSTANT_REVIEW_USERSEGMENT 		= "BS_CONSTANT_REVIEW_USERSEGMENT";
		public final static String BS_CONSTANT_REVIEW_TYPE_ROOM 		= "BS_CONSTANT_REVIEW_TYPE_ROOM";
		public final static String BS_CONSTANT_REVIEW_STAY_NIGHTS 		= "BS_CONSTANT_REVIEW_STAY_NIGHTS";
		public final static String BS_CONSTANT_REVIEW_WITH_PET	 		= "BS_CONSTANT_REVIEW_WITH_PET";
//		public final static String BS_CONSTANT_REVIEW_SUBSEGMENT 		= "BS_CONSTANT_REVIEW_SUBSEGMENT";
		public final static String BS_CONSTANT_REVIEW_FROM 				= "BS_CONSTANT_REVIEW_FROM";
		public final static String BS_CONSTANT_REVIEW_DATE 				= "BS_CONSTANT_REVIEW_DATE";
		public final static String BS_CONSTANT_REVIEW_LANG 				= "BS_CONSTANT_REVIEW_LANG";
		public final static String BS_CONSTANT_REVIEW_REVIEWGOOD 		= "BS_CONSTANT_REVIEW_REVIEWGOOD";
		public final static String BS_CONSTANT_REVIEW_REVIEWBAD 		= "BS_CONSTANT_REVIEW_REVIEWBAD";
		public final static String BS_CONSTANT_REVIEW_SCORE 			= "BS_CONSTANT_REVIEW_SCORE";
		public final static String BS_CONSTANT_REVIEW_USERSEGMENT_UNKNOWN	= "BS_CONSTANT_REVIEW_USERSEGMENT_UNKNOWN";

		// SERVICES
		public final static String BS_CONSTANT_SERVICE_FREEWIFI			= "BS_CONSTANT_SERVICE_FREEWIFI";
		public final static String BS_CONSTANT_SERVICE_FREEPARKING		= "BS_CONSTANT_SERVICE_FREEPARKING";
		public final static String BS_CONSTANT_SERVICE_ACTIVITIES		= "BS_CONSTANT_SERVICE_ACTIVITIES";
		public final static String BS_CONSTANT_SERVICE_PETS_ALLOWED		= "BS_CONSTANT_SERVICE_PETS_ALLOWED";
		
		
	/**
	 * CONFIGURATIONS
	 */
		// Configuration Thread Manager
		public final static String THREAD_COUNT 								= "THREAD_COUNT";
		public static final String TIMEOUT 										= "HTTP_TIMEOUT";
		public static final String RETRY_TIMEOUT								= "RETRY_TIMEOUT";
		
		// Booking Configuration
		public final static String BK_HOST 										= "BK_HOST";
		public final static String BK_PORT 										= "BK_PORT";
		public final static String BK_PATH_RATINGS 								= "BK_PATH_RATINGS";
		public final static String BK_PATH_REVIEWS								= "BK_PATH_REVIEWS";
		public final static String BK_PATH_PRICES 								= "BK_PATH_PRICES";
		public final static String BK_PATH_PRICES_HDE							= "BK_PATH_PRICES_HDE";		
		public final static String BK_PATH_SERVICES								= "BK_PATH_SERVICES";
		public final static String BK_USER_AGENT								= "BK_USER_AGENT";
		public final static String BK_ACCEPT_LANG								= "BK_ACCEPT_LANG";
		
		// URL replace
		public final static String BK_REPLACE_REGION							= "BK_REPLACE_REGION";
		public final static String BK_REPLACE_PROPERTYTYPE						= "BK_REPLACE_PROPERTYTYPE";
		public final static String BK_REPLACE_ACCTYPE							= "BK_REPLACE_ACCTYPE";
		public final static String BK_REPLACE_RADIUS							= "BK_REPLACE_RADIUS";
		public final static String BK_REPLACE_ACCOMMODATIONID							= "BK_REPLACE_ACCOMMODATIONID";
		public final static String BK_REPLACE_COUNTRY							= "BK_REPLACE_COUNTRY";
		public final static String BK_REPLACE_INDATE							= "BK_REPLACE_INDATE";
		public final static String BK_REPLACE_OUTDATE							= "BK_REPLACE_OUTDATE";
		public final static String BK_REPLACE_USER_SEGMENT						= "BK_REPLACE_USER_SEGMENT";
		public final static String BK_REPLACE_ROWSTART							= "BK_REPLACE_ROWSTART";
		public final static String BK_REPLACE_NROWS								= "BK_REPLACE_NROWS";
		public final static String BK_REPLACE_ATTRIBUTE							= "BK_REPLACE_ATTRIBUTE";

		// Scraping conditions
		public final static String SCR_DATES 									= "SCR_DATES";
		public final static String SCR_LENGTH_OF_STAY 							= "SCR_LENGTH_OF_STAY";
		public final static String SCR_COUNTRY									= "SCR_COUNTRY";
		
		// SCraping ratings & reviews conditions
		public final static String SCR_PRICES_HDE_PROPERTY_TYPE					= "SCR_PRICES_HDE_PROPERTY_TYPE";
		public final static String SCR_PRICES_HDE_RADIUS						= "SCR_PRICES_HDE_RADIUS";
		public final static String SCR_PRICES_HDE_ROWSTART						= "SCR_PRICES_HDE_ROWSTART";
		public final static String SCR_PRICES_HDE_ROWS							= "SCR_PRICES_HDE_ROWS";
		public final static String SCR_RATINGS_AVAILABLE_USER_SEGMENTS			= "SCR_RATINGS_AVAILABLE_USER_SEGMENTS";
		public final static String SCR_RATINGS_AVAILABLE_ATTRIBUTES				= "SCR_RATINGS_AVAILABLE_ATTRIBUTES";
		public final static String SCR_REVIEWS_ROWSTART							= "SCR_REVIEWS_ROWSTART";
		public final static String SCR_REVIEWS_ROWS	 							= "SCR_REVIEWS_ROWS";
		
		// Regex configuration
		public final static String REGEX_REVIEWS_SUBSEGMENT						= "REGEX_ACCOMMODATION_REVIEW_SUBSEGMENT";
		public final static String REGEX_REVIEWS_STAY_NIGHTS					= "REGEX_ACCOMMODATION_REVIEW_STAY_NIGHTS";
		public final static String REGEX_PRICES_CHILDREN_AMOUNT					= "REGEX_PRICES_CHILDREN_AMOUNT";
		
		// Selectors configuration
		public final static String SELECTOR_REGION_ACCOMMODATION_LIST					= "REGION_ACCOMMODATION_LIST";
		
		public final static String SELECTOR_REGION_IS_HOTEL								= "REGION_IS_HOTEL";
		
		public final static String SELECTOR_REGION_ACCOMMODATION_ID_CHANNEL_ATTR		= "REGION_ACCOMMODATION_ID_CHANNEL_ATTR";
		public final static String SELECTOR_REGION_ACCOMMODATION_ID_CHANNEL_PREFIX		= "REGION_ACCOMMODATION_ID_CHANNEL_PREFIX";
		
		public final static String[] SELECTOR_REGION_ACCOMMODATION_NAME					= new String[]{"REGION_ACCOMMODATION_NAME_1",
																								"REGION_ACCOMMODATION_NAME_2"};
		public final static String[] SELECTOR_REGION_ACCOMMODATION_URL					= new String[]{"REGION_ACCOMMODATION_URL_1",
																								"REGION_ACCOMMODATION_URL_2"};
		public final static String[] SELECTOR_REGION_ACCOMMODATION_ROOM_TYPE			= new String[]{"REGION_ACCOMMODATION_ROOM_TYPE_1",
																								"REGION_ACCOMMODATION_ROOM_TYPE_2"};
		public final static String[] SELECTOR_REGION_ACCOMMODATION_PRICE				= new String[]{"REGION_ACCOMMODATION_PRICE_1",
																								"REGION_ACCOMMODATION_PRICE_2"};
		public final static String[] SELECTOR_REGION_ACCOMMODATION_COORDS					= new String[]{"REGION_ACCOMMODATION_COORDS_1",
																								"REGION_ACCOMMODATION_COORDS_2"};
		//public final static String SELECTOR_REGION_ACCOMMODATION_CATEGORY				= "REGION_ACCOMMODATION_CATEGORY";
		public final static String[] SELECTOR_REGION_ACCOMMODATION_CATEGORY				= new String[]{"REGION_ACCOMMODATION_CATEGORY_1",
																								"REGION_ACCOMMODATION_CATEGORY_2"};
		public final static String[] SELECTOR_REGION_APARTMENT_MAX_PEOPLE					= new String[]{"REGION_APARTMENT_MAX_PEOPLE_1", "REGION_APARTMENT_MAX_PEOPLE_2"};
		
		public final static String PROPERTY_ACCOMMODATION_CATEGORY						= "PROPERTY_ACCOMMODATION_CATEGORY";
		
		public final static String SELECTOR_ACCOMMODATION_PRODUCTS						= "ACCOMMODATION_PRODUCTS";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_NAME					= "ACCOMMODATION_PRODUCT_NAME";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_BREAKFAST				= "ACCOMMODATION_PRODUCT_BREAKFAST";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_BREAKFAST_PRICE		= "ACCOMMODATION_PRODUCT_BREAKFAST_PRICE";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_HALF					= "ACCOMMODATION_PRODUCT_HALF";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_FULL					= "ACCOMMODATION_PRODUCT_FULL";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_ALL					= "ACCOMMODATION_PRODUCT_ALL";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_FREE_CANCELLATION		= "ACCOMMODATION_PRODUCT_FREE_CANCELLATION";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_PAY_STAY				= "ACCOMMODATION_PRODUCT_PAY_STAY";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_PAY_LATER				= "ACCOMMODATION_PRODUCT_PAY_LATER";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_NON_REFUNDABLE		= "ACCOMMODATION_PRODUCT_NON_REFUNDABLE";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_PRICE					= "ACCOMMODATION_PRODUCT_PRICE";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_OCCUPANCY				= "ACCOMMODATION_PRODUCT_OCCUPANCY";
		public final static String SELECTOR_ACCOMMODATION_PRODUCT_CHILD					= "ACCOMMODATION_PRODUCT_CHILD";
	
		public final static String SELECTOR_ACCOMMODATION_RATING						= "ACCOMMODATION_RATING";
		public final static String SELECTOR_ACCOMMODATION_RATING_P						= "ACCOMMODATION_RATING_P";
		public final static String SELECTOR_ACCOMMODATION_RATING_ATTRIBUTE				= "ACCOMMODATION_RATING_ATTRIBUTE";
		public final static String SELECTOR_ACCOMMODATION_RATING_ATTRIBUTE_VALUE		= "ACCOMMODATION_RATING_ATTRIBUTE_VALUE";
		
		public final static String SELECTOR_ACCOMMODATION_REVIEW_LIST 					= "ACCOMMODATION_REVIEW_LIST";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_TYPE_TRIP 				= "ACCOMMODATION_REVIEW_TYPE_TRIP";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_SEGMENT 				= "ACCOMMODATION_REVIEW_SEGMENT";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_TYPE_ROOM 				= "ACCOMMODATION_REVIEW_TYPE_ROOM";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_STAY_NIGHTS 			= "ACCOMMODATION_REVIEW_STAY_NIGHTS";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_WITH_PET	 			= "ACCOMMODATION_REVIEW_WITH_PET";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_FROM 					= "ACCOMMODATION_REVIEW_FROM";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_DATE 					= "ACCOMMODATION_REVIEW_DATE";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_GOOD 					= "ACCOMMODATION_REVIEW_GOOD";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_BAD 					= "ACCOMMODATION_REVIEW_BAD";
		public final static String SELECTOR_ACCOMMODATION_REVIEW_SCORE 					= "ACCOMMODATION_REVIEW_SCORE";
		
		public final static String SELECTOR_ACCOMMODATION_SERVICES						= "ACCOMMODATION_SERVICES";
		public final static String SELECTOR_ACCOMMODATION_SERVICE_INTERNET_FREE_WIFI	= "ACCOMMODATION_SERVICE_INTERNET_FREE_WIFI";
		public final static String SELECTOR_ACCOMMODATION_SERVICE_PARKING_FREE			= "ACCOMMODATION_SERVICE_PARKING_FREE";
		public final static String SELECTOR_ACCOMMODATION_SERVICE_PETS_ALLOWED			= "ACCOMMODATION_SERVICE_PETS_ALLOWED";
		public final static String SELECTOR_ACCOMMODATION_SERVICE_ACTIVITIES			= "ACCOMMODATION_SERVICE_ACTIVITIES";
		
		// Descripciones de error
		public final static String BS_ERROR_ROOM_TYPE_NOT_MATCH					= "BS_ROOM_TYPE_NOT_MATCH";
		public final static String BS_ERROR_SELECTOR_FAILED						= "BS_SELECTOR_FAILED";
		
}
